In [86]:
rains = (0,1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
     11, 12, 13, 333, 15, 16, 17, 18,
     19, 20,30,22,23,24,3335,26,27,28,232323239)

print(str(rains.index(max(rains))) + "-ого Февраля выпало самое большое кол-во осадков")
    


29-ого Февраля выпало самое большое кол-во осадков


In [210]:
import numpy as np

array = np.random.randint(0, 100, (5, 5))
print("Исходный массив:\n", array)

max_value = np.max(array)
max_index = np.unravel_index(np.argmax(array, axis=None), array.shape)


if max_index[0] != 0:
    array[[0, max_index[0]]] = array[[max_index[0], 0]]


if max_index[1] != 0:
    array[:, [0, max_index[1]]] = array[:, [max_index[1], 0]]

print("Массив после перемещения наибольшего элемента:\n", array)

Исходный массив:
 [[18 64 87  4 16]
 [38  2 45 12 28]
 [ 2 66 13 19 44]
 [49 51 21 10 44]
 [23 23 11 54 18]]
Массив после перемещения наибольшего элемента:
 [[87 64 18  4 16]
 [45  2 38 12 28]
 [13 66  2 19 44]
 [21 51 49 10 44]
 [11 23 23 54 18]]


In [228]:
my_list = [1, 2, 3, 3, 9, 6, 7, 8, 9, 10,]
unique_elements = []

for i in my_list:
    if  my_list.count(i) == 1:
        unique_elements.append(i)

print(unique_elements)
        

[1, 2, 6, 7, 8, 10]


In [252]:
more = set('qwertyuiop[]asdfghjklzxcvbnm/')
print(more)
print('Различных символов: '+str(len(more)))

{'m', 'i', 'w', 'o', 'q', 'v', 'e', 'u', 'g', 'h', 's', '[', 'j', '/', 'z', 'd', 'b', 'y', 'r', 'l', 't', ']', 'f', 'p', 'a', 'x', 'k', 'c', 'n'}
Различных символов: 29


In [269]:
dictionary = {'a':3, 'b':6, 'c':4}

def result_mult(input_dict):
    result = 1
    for value in input_dict.values():
        result *= value
    return result
        
product = result_mult(dictionary)
print("Произведение всех значений словаря:", product)

Произведение всех значений словаря: 72
